apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: github-actions-role
  namespace: ecommerce

rules:

- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - list
    - watch
    - update
    - patch

- apiGroups:
    - ""
  resources:
    - services
    - configmaps
    - secrets
    - pods
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete

- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete