apiVersion: v1
kind: ConfigMap

metadata:
  name: ecommerce-config
  namespace: ecommerce

data:
  DB_URL: "jdbc:mysql://mysql-service:3306/ecommerce"
  DB_USERNAME: "root"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"